[package]
edition = "2021"
name = "rust_order_book"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
reqwest = {version = "0.11", features = ["json"]}
tokio = {version = "1", features = ["full"]}
